### ISSUE TITLE
Quote IWTS Artist ETL

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-iwts#2]
Please look at the IWTS documentation in https://github.com/culturecreates/artsdata-planet-iwts/issues/1 and provide a rough estimate.  Just a first pass of loading the data into Artsdata from the API.  After the data is loaded we can look more closely at the mapping of properties to existing ontologies.

**Comment by dev-aravind** [comment]
@saumier 

Rough estimate:

Set up ontorefine and transform the data to RDF - 3h
Create a new workflow to implement the transformation - 3h
Push to Artsdata and Testing - 2h

Total - 8h
