### ISSUE TITLE
IWTS first pass ETL

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-iwts#3]
Using the IWTS API with the key sent separately
https://iwanttoshowcase.ca/apiiwts.php?api_key=

**Comment by dev-aravind** [comment]
@saumier The [data](https://kg.artsdata.ca/en/query/show?title=Person%20entities%20in%20iwts-ca&sparql=list_people&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-iwts/iwts-ca) is now up in Artsdata. Let me know if you need any changes.
