### ISSUE TITLE
IWTS refine properties

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-iwts#4]
Refer to document **I Want To Showcase’s Data Model for Open Data**
https://docs.google.com/document/d/14SHgIWuItkp8lnmeculEctfyLc0YV6CVuZRX4e8h0q0/edit?tab=t.0

### Summary of RDF transformation 

- Performerid → Generate URI using template ‘https://iwanttoshowcase.ca/performerid/####' (uri)
- Performer_type → rdf:type = schema:Person | schema:PerformingGroup | schema:Organization (uri)
- Performer_description → schema:description = (string)
- Performer_name → schema:name = (string)
- Performer_country → schema:workLocation/schema:address/schema:addressCountry = (string)
- Performer_province → schema:workLocation/schema:address/schema:addressRegion = (string)
- Performer_pronouns → https://iwanttoshowcase.ca/vocabulary#pronouns = (string)
- Performer_birth_country → schema:birthPlace/schema:address/schema:addressCountry = (string)
- Performer_birth_province → schema:birthPlace/schema:address/schema:addressRegion = (string)
- Performer_website1 → schema:url = (uri)
- Performer_website2 → schema:sameAs =  (uri)
- Performer_website3 → schema:sameAs = (uri)
- Performer_website4 → schema:sameAs = (uri)
- Performer_website5 → schema:sameAs = (uri)
- Performance_category → schema:knowsAbout = mapped to Artsdata Event Type (uri) 
- Performance_subgenre1 → schema:genre = (string)
- Performer_identify → MISSING? https://iwanttoshowcase.ca/vocabulary#performerIdentify = (string)
- Performer_self_identify → MISSING? https://iwanttoshowcase.ca/vocabulary#performerSelfIdentify = (string)

**Comment by saumier** [comment]
@dev-aravind I would like to give a push to complete this WO. Here are the remaining tasks:

- [x] Add the script and Docker compose files to run OntoRefine locally
- [x] Refine the RDF transformation as per my comments in the [IWTS Open Data Model](https://docs.google.com/document/d/14SHgIWuItkp8lnmeculEctfyLc0YV6CVuZRX4e8h0q0/edit?tab=t.0) document

**Comment by dev-aravind** [comment]
@saumier You can find the organizations [here](https://kg.artsdata.ca/en/query/show?title=Organization%20entities%20in%20iwts-ca&sparql=list_organizations&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-iwts/iwts-ca) and the people [here](https://kg.artsdata.ca/en/query/show?title=Person%20entities%20in%20iwts-ca&sparql=list_people&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-iwts/iwts-ca) for IWTS.

A new script to run OntoRefine locally is also added to the repository. Let me know if you need any more changes.

**Comment by saumier** [comment]
@dev-aravind 

Thanks for the links. It made is very easy for me to test :-)

Here are some issues to correct:
- [x] Do not add an empty <> for schema:sameAs link in this [event](https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fiwanttoshowcase.ca%2Fperformerid%2F4358) because it results in `http://example.com/base/` which is wrong
- [x] Do not leave empty blank address nodes for schema:workPlace or schema:birthPlace like in this [event](https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fiwanttoshowcase.ca%2Fperformerid%2F6821).

**NOTE**: It is important to not store empty strings when using OntoRefine and RDF mapping. It can lead to unexpected results like adding `http://example.com/base/`.  This is a repeat mis-configuration of OntoRefine that I am seeing. The problems I found above should go away if you edit the ontorefine-config.json and set ` "storeEmptyStrings": false`.  Please confirm that this works as the way to fix the issues I found. Thx.

**Comment by dev-aravind** [comment]
@saumier Both of these issues were fixed by flipping the storeEmptyStrings value, you can test the same performers you mentioned in the previous comment. Thanks for pointing that out.

**Comment by saumier** [comment]
@dev-aravind Thanks. Looks great.

**Comment by saumier** [comment]
@dev-aravind In today's meeting we discovered an issue: when the entity is a schema:PerformingGroup or schema:Organization then the performerCountry and performerProvince should use the property schema:location instead of schema:workLocation because the domain of schema:workLocation is ONLY type schema:Person.

**Comment by dev-aravind** [comment]
@saumier This is fixed now. Please review this and let me know if you need any more changes.

**Comment by saumier** [comment]
@dev-aravind Perfect. Thx.
